apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency-server-mcp
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: currency-server-mcp
    account: currency-server-mcp
